# Generated by Django 3.2.10 on 2021-12-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_auto_20211208_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_regNo',
        ),
        migrations.AddField(
            model_name='employee',
            name='Address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
    ]
